# Generated by Django 2.1 on 2019-04-24 14:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190424_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 14, 38, 45, 187145, tzinfo=utc)),
        ),
    ]
