# Generated by Django 2.1 on 2019-04-24 15:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190424_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 15, 4, 58, 683057, tzinfo=utc)),
        ),
    ]
